In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = np.random.randn(4,3)

In [ ]:
data

array([[ 0.48220896,  0.5263247 , -0.76775641],
       [-0.99494136, -0.27922278,  0.24158642],
       [ 1.21713362, -1.88496774, -1.05784427],
       [ 0.55232928, -0.13904497, -0.27197205]])

In [ ]:
data_frame = pd.DataFrame(data)

In [ ]:
data_frame

          0         1         2
0  0.482209  0.526325 -0.767756
1 -0.994941 -0.279223  0.241586
2  1.217134 -1.884968 -1.057844
3  0.552329 -0.139045 -0.271972

In [ ]:
type(data_frame)

pandas.core.frame.DataFrame

In [ ]:
data_frame[0]

0    0.482209
1   -0.994941
2    1.217134
3    0.552329
Name: 0, dtype: float64

In [ ]:
type(data_frame[0])

pandas.core.series.Series

In [ ]:
new_df = pd.DataFrame(data, index = ["Ömer","Arda","Salih","Mehmet"], columns = ["Salary","Age","Seniority"])

In [ ]:
new_df

          Salary       Age  Seniority
Ömer    0.482209  0.526325  -0.767756
Arda   -0.994941 -0.279223   0.241586
Salih   1.217134 -1.884968  -1.057844
Mehmet  0.552329 -0.139045  -0.271972

In [ ]:
new_df["Age"]

Ömer      0.526325
Arda     -0.279223
Salih    -1.884968
Mehmet   -0.139045
Name: Age, dtype: float64

In [ ]:
new_df[["Age", "Salary"]]

             Age    Salary
Ömer    0.526325  0.482209
Arda   -0.279223 -0.994941
Salih  -1.884968  1.217134
Mehmet -0.139045  0.552329

In [ ]:
new_df.loc["Ömer"]

Salary       0.482209
Age          0.526325
Seniority   -0.767756
Name: Ömer, dtype: float64

In [ ]:
new_df.iloc[0]

Salary       0.482209
Age          0.526325
Seniority   -0.767756
Name: Ömer, dtype: float64

In [ ]:
new_df

          Salary       Age  Seniority
Ömer    0.482209  0.526325  -0.767756
Arda   -0.994941 -0.279223   0.241586
Salih   1.217134 -1.884968  -1.057844
Mehmet  0.552329 -0.139045  -0.271972

In [ ]:
 new_df.iloc[:,0]

Ömer      0.482209
Arda     -0.994941
Salih     1.217134
Mehmet    0.552329
Name: Salary, dtype: float64

In [ ]:
new_df["Extra"] = 10

In [ ]:
new_df

          Salary       Age  Seniority  Extra
Ömer    0.482209  0.526325  -0.767756     10
Arda   -0.994941 -0.279223   0.241586     10
Salih   1.217134 -1.884968  -1.057844     10
Mehmet  0.552329 -0.139045  -0.271972     10

In [ ]:
new_df.drop("Extra", axis=1)

          Salary       Age  Seniority
Ömer    0.482209  0.526325  -0.767756
Arda   -0.994941 -0.279223   0.241586
Salih   1.217134 -1.884968  -1.057844
Mehmet  0.552329 -0.139045  -0.271972

In [ ]:
new_df

          Salary       Age  Seniority  Extra
Ömer    0.482209  0.526325  -0.767756     10
Arda   -0.994941 -0.279223   0.241586     10
Salih   1.217134 -1.884968  -1.057844     10
Mehmet  0.552329 -0.139045  -0.271972     10

In [ ]:
new_df.drop("Extra", axis = 1 , inplace = True)

In [ ]:
new_df

          Salary       Age  Seniority
Ömer    0.482209  0.526325  -0.767756
Arda   -0.994941 -0.279223   0.241586
Salih   1.217134 -1.884968  -1.057844
Mehmet  0.552329 -0.139045  -0.271972

In [ ]:
new_df["Mehmet"] = 10

In [34]:
new_df.drop("Mehmet")

         Salary       Age  Seniority  Mehmet
Ömer   0.482209  0.526325  -0.767756      10
Arda  -0.994941 -0.279223   0.241586      10
Salih  1.217134 -1.884968  -1.057844      10

In [35]:
new_df

          Salary       Age  Seniority  Mehmet
Ömer    0.482209  0.526325  -0.767756      10
Arda   -0.994941 -0.279223   0.241586      10
Salih   1.217134 -1.884968  -1.057844      10
Mehmet  0.552329 -0.139045  -0.271972      10

In [36]:
new_df.drop("Mehmet", axis = 1 , inplace = True )

In [37]:
new_df

          Salary       Age  Seniority
Ömer    0.482209  0.526325  -0.767756
Arda   -0.994941 -0.279223   0.241586
Salih   1.217134 -1.884968  -1.057844
Mehmet  0.552329 -0.139045  -0.271972

In [38]:
new_df.drop("Mehmet")

         Salary       Age  Seniority
Ömer   0.482209  0.526325  -0.767756
Arda  -0.994941 -0.279223   0.241586
Salih  1.217134 -1.884968  -1.057844

In [39]:
new_df

          Salary       Age  Seniority
Ömer    0.482209  0.526325  -0.767756
Arda   -0.994941 -0.279223   0.241586
Salih   1.217134 -1.884968  -1.057844
Mehmet  0.552329 -0.139045  -0.271972

In [40]:
new_df.loc["Ömer"]

Salary       0.482209
Age          0.526325
Seniority   -0.767756
Name: Ömer, dtype: float64

In [42]:
new_df.loc["Ömer"]["Salary"]

np.float64(0.4822089558662433)

In [52]:
new_df.loc["Ömer","Salary"]

np.float64(31.0)

In [53]:
new_df.loc["Ömer","Salary"] = 31

In [54]:
new_df

           Salary       Age  Seniority
Ömer    31.000000  0.526325  -0.767756
Arda    -0.994941 -0.279223   0.241586
Salih    1.217134 -1.884968  -1.057844
Mehmet   0.552329 -0.139045  -0.271972

In [55]:
new_df > 0

        Salary    Age  Seniority
Ömer      True   True      False
Arda     False  False       True
Salih     True  False      False
Mehmet    True  False      False

In [56]:
boolean_frame = new_df > 0

In [58]:
new_df[boolean_frame]

           Salary       Age  Seniority
Ömer    31.000000  0.526325        NaN
Arda          NaN       NaN   0.241586
Salih    1.217134       NaN        NaN
Mehmet   0.552329       NaN        NaN

In [59]:
new_df[new_df > 0]

           Salary       Age  Seniority
Ömer    31.000000  0.526325        NaN
Arda          NaN       NaN   0.241586
Salih    1.217134       NaN        NaN
Mehmet   0.552329       NaN        NaN

In [60]:
new_df[new_df["Salary"] > 1]

          Salary       Age  Seniority
Ömer   31.000000  0.526325  -0.767756
Salih   1.217134 -1.884968  -1.057844

In [61]:
new_df

           Salary       Age  Seniority
Ömer    31.000000  0.526325  -0.767756
Arda    -0.994941 -0.279223   0.241586
Salih    1.217134 -1.884968  -1.057844
Mehmet   0.552329 -0.139045  -0.271972

In [62]:
new_df.reset_index()

    index     Salary       Age  Seniority
0    Ömer  31.000000  0.526325  -0.767756
1    Arda  -0.994941 -0.279223   0.241586
2   Salih   1.217134 -1.884968  -1.057844
3  Mehmet   0.552329 -0.139045  -0.271972

In [63]:
new_df

           Salary       Age  Seniority
Ömer    31.000000  0.526325  -0.767756
Arda    -0.994941 -0.279223   0.241586
Salih    1.217134 -1.884968  -1.057844
Mehmet   0.552329 -0.139045  -0.271972

In [64]:
reset_frame = new_df.reset_index()

In [65]:
reset_frame

    index     Salary       Age  Seniority
0    Ömer  31.000000  0.526325  -0.767756
1    Arda  -0.994941 -0.279223   0.241586
2   Salih   1.217134 -1.884968  -1.057844
3  Mehmet   0.552329 -0.139045  -0.271972

In [67]:
reset_frame.loc[0]

index            Ömer
Salary           31.0
Age          0.526325
Seniority   -0.767756
Name: 0, dtype: object

In [68]:
new_indices = ["Atil","Zey","Atil","Meh"]

In [69]:
new_df["NewIndex"] = new_indices

In [70]:
new_df

           Salary       Age  Seniority NewIndex
Ömer    31.000000  0.526325  -0.767756     Atil
Arda    -0.994941 -0.279223   0.241586      Zey
Salih    1.217134 -1.884968  -1.057844     Atil
Mehmet   0.552329 -0.139045  -0.271972      Meh

In [71]:
new_df.set_index("NewIndex", inplace= True)

In [72]:
new_df

             Salary       Age  Seniority
NewIndex
Atil      31.000000  0.526325  -0.767756
Zey       -0.994941 -0.279223   0.241586
Atil       1.217134 -1.884968  -1.057844
Meh        0.552329 -0.139045  -0.271972

In [73]:
new_df.loc["Atil"]

             Salary       Age  Seniority
NewIndex
Atil      31.000000  0.526325  -0.767756
Atil       1.217134 -1.884968  -1.057844

In [75]:
# multi index